# numpy.array中的运算
给定一个向量，让向量中每一个数乘以2
a = (0, 1, 2)
a*2 = (0, 2, 4)

In [1]:
import numpy as np
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(2 * e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
n = 1000000
L = [i for i in range(n)]

In [7]:
%%time
A = []
for e in L:
    A.append(2 * e)

Wall time: 184 ms


In [8]:
%%time
A = [2 * e for e in L]

Wall time: 130 ms


In [12]:
L = np.arange(n)

In [13]:
%%time
A = np.array(2 *e for e in L)

Wall time: 21.7 ms


In [14]:
%%time
A = 2 * L

Wall time: 0 ns


In [15]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [16]:
n = 10
L = np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Universal Functions

In [17]:
X = np.arange(1, 16).reshape((3, 5))
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
X + 1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [19]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [20]:
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [21]:
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [23]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [25]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [26]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
np.sin(X)  # or cos tin etc.

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [28]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [29]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

### 矩阵运算

In [30]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [31]:
B = np.full((2, 2), 10)
B

array([[10, 10],
       [10, 10]])

In [32]:
A + B

array([[10, 11],
       [12, 13]])

In [33]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [34]:
A * B

array([[ 0, 10],
       [20, 30]])

In [36]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

In [37]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [38]:
A.T

array([[0, 2],
       [1, 3]])

In [39]:
C = np.full((3, 3), 666)

In [40]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [41]:
A.dot(C)

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### 向量和矩阵的运算

In [42]:
v = np.array([1, 2])

In [43]:
A

array([[0, 1],
       [2, 3]])

In [44]:
v + A

array([[1, 3],
       [3, 5]])

In [45]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [46]:
np.vstack([v] * A.shape[0]) + A

array([[1, 3],
       [3, 5]])

In [47]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [48]:
np.tile(v,(1, 2))

array([[1, 2, 1, 2]])

In [49]:
np.tile(v, (2, 1)) + A

array([[1, 3],
       [3, 5]])

In [50]:
v

array([1, 2])

In [51]:
A

array([[0, 1],
       [2, 3]])

In [52]:
v * A

array([[0, 2],
       [2, 6]])

In [53]:
v.dot(A)

array([4, 7])

In [54]:
A.dot(v)

array([2, 8])

In [56]:
A.dot(v).shape

(2,)

### 矩阵的逆

In [57]:
A

array([[0, 1],
       [2, 3]])

In [58]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [59]:
invA = np.linalg.inv(A)  # 至少是方阵
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [60]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [61]:
X = np.arange(16).reshape((2, 8))
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [63]:
pinvX = np.linalg.pinv(X)  # 非方阵求伪逆矩阵
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [64]:
pinvX.shape

(8, 2)

In [65]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])

In [66]:
pinvX.dot(X)

array([[ 4.16666667e-01,  3.33333333e-01,  2.50000000e-01,
         1.66666667e-01,  8.33333333e-02,  4.78783679e-16,
        -8.33333333e-02, -1.66666667e-01],
       [ 3.33333333e-01,  2.73809524e-01,  2.14285714e-01,
         1.54761905e-01,  9.52380952e-02,  3.57142857e-02,
        -2.38095238e-02, -8.33333333e-02],
       [ 2.50000000e-01,  2.14285714e-01,  1.78571429e-01,
         1.42857143e-01,  1.07142857e-01,  7.14285714e-02,
         3.57142857e-02,  2.84494650e-16],
       [ 1.66666667e-01,  1.54761905e-01,  1.42857143e-01,
         1.30952381e-01,  1.19047619e-01,  1.07142857e-01,
         9.52380952e-02,  8.33333333e-02],
       [ 8.33333333e-02,  9.52380952e-02,  1.07142857e-01,
         1.19047619e-01,  1.30952381e-01,  1.42857143e-01,
         1.54761905e-01,  1.66666667e-01],
       [-5.84467136e-17,  3.57142857e-02,  7.14285714e-02,
         1.07142857e-01,  1.42857143e-01,  1.78571429e-01,
         2.14285714e-01,  2.50000000e-01],
       [-8.33333333e-02, -2.380952

### 聚合操作

In [67]:
L = np.random.random(100)

In [68]:
L

array([0.20144368, 0.73207737, 0.08336247, 0.13702619, 0.18742917,
       0.34770219, 0.97878083, 0.73271101, 0.98854487, 0.49800002,
       0.12715933, 0.96207549, 0.32809678, 0.80045338, 0.69741294,
       0.11774226, 0.86576493, 0.24724428, 0.19355926, 0.45420265,
       0.72689846, 0.85446351, 0.88619779, 0.62250347, 0.76827342,
       0.62471621, 0.76650565, 0.24901014, 0.42567301, 0.83572287,
       0.25408579, 0.9212489 , 0.31706542, 0.56274705, 0.30828375,
       0.53518404, 0.36032901, 0.38443436, 0.2571955 , 0.58434172,
       0.47992567, 0.58358791, 0.56681661, 0.68925453, 0.55459139,
       0.5615166 , 0.89816345, 0.57299173, 0.08139469, 0.25907671,
       0.37708813, 0.43970178, 0.86267242, 0.96302954, 0.92177234,
       0.04409426, 0.60088853, 0.46975655, 0.33497787, 0.66224402,
       0.24625791, 0.96252045, 0.91407109, 0.2720991 , 0.78513814,
       0.21152032, 0.75482542, 0.97302714, 0.97063372, 0.29400414,
       0.2097607 , 0.27681454, 0.10585063, 0.07004407, 0.94717

In [69]:
sum(L)

54.063534661934746

In [70]:
np.sum(L)

54.06353466193476

In [71]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

96.1 ms ± 2.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.23 ms ± 73.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [72]:
np.max(big_array)

0.999999919904373

In [73]:
np.min(big_array)

3.056197823703144e-07

In [74]:
big_array.max()

0.999999919904373

In [75]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
np.sum(X)

120

In [77]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [78]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [79]:
np.prod(X)

0

In [80]:
np.prod(X + 1)

2004189184

In [81]:
np.mean(X)

7.5

In [83]:
np.median(X)

7.5

In [84]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [85]:
np.median(v)

2.0

In [86]:
np.percentile(big_array, q=50)

0.5000584636117871

In [87]:
np.mean(big_array)

0.500142971863106

In [88]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

3.056197823703144e-07
0.25011313159322773
0.5000584636117871
0.7501196311793339
0.999999919904373


In [89]:
np.var(big_array)

0.08332068712060664

In [90]:
np.std(big_array)

0.28865322988078035

In [91]:
x = np.random.normal(0, 1, size=100000)

In [92]:
np.mean(x)

0.0013334759471931227

In [93]:
np.std(x)

1.0019553837923545

### 索引

In [94]:
np.min(x)

-4.557490881497047

In [95]:
np.argmin(x)

33331

In [96]:
np.argmax(x)

94703

In [97]:
x[94703]

4.105493914244517

In [98]:
np.max(x)

4.105493914244517

### 排序和使用索引

In [100]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [101]:
np.random.shuffle(x)

In [102]:
x

array([15, 11,  7,  9,  8,  2, 12, 14, 10, 13,  3,  5,  4,  6,  0,  1])

In [103]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [104]:
x

array([15, 11,  7,  9,  8,  2, 12, 14, 10, 13,  3,  5,  4,  6,  0,  1])

In [105]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [106]:
X = np.random.randint(10, size=(4, 4))
X

array([[4, 0, 9, 5],
       [3, 0, 9, 5],
       [6, 6, 7, 5],
       [9, 8, 5, 8]])

In [107]:
np.sort(X)

array([[0, 4, 5, 9],
       [0, 3, 5, 9],
       [5, 6, 6, 7],
       [5, 8, 8, 9]])

In [108]:
np.sort(X, axis=1)

array([[0, 4, 5, 9],
       [0, 3, 5, 9],
       [5, 6, 6, 7],
       [5, 8, 8, 9]])

In [109]:
np.sort(X, axis=0)

array([[3, 0, 5, 5],
       [4, 0, 7, 5],
       [6, 6, 9, 5],
       [9, 8, 9, 8]])

In [110]:
np.random.shuffle(x)
x

array([ 8,  7, 15,  5, 12,  3, 14,  1,  4, 13,  6,  9,  0, 10,  2, 11])

In [111]:
np.argsort(x)

array([12,  7, 14,  5,  8,  3, 10,  1,  0, 11, 13, 15,  4,  9,  6,  2],
      dtype=int64)

In [112]:
np.partition(x, 3)

array([ 1,  0,  2,  3,  4,  5,  6,  7,  8, 13, 14,  9, 12, 10, 15, 11])

In [113]:
np.argpartition(x, 3)

array([ 7, 12, 14,  5,  8,  3, 10,  1,  0,  9,  6, 11,  4, 13,  2, 15],
      dtype=int64)

In [114]:
X

array([[4, 0, 9, 5],
       [3, 0, 9, 5],
       [6, 6, 7, 5],
       [9, 8, 5, 8]])

In [115]:
np.argsort(X, axis=1)

array([[1, 0, 3, 2],
       [1, 0, 3, 2],
       [3, 0, 1, 2],
       [2, 1, 3, 0]], dtype=int64)

In [116]:
np.argsort(X, axis=0)

array([[1, 0, 3, 0],
       [0, 1, 2, 1],
       [2, 2, 0, 2],
       [3, 3, 1, 3]], dtype=int64)

In [117]:
np.argpartition(X, 2, axis=1)

array([[1, 0, 3, 2],
       [1, 0, 3, 2],
       [3, 1, 0, 2],
       [2, 1, 3, 0]], dtype=int64)

### Fancy Indexing

In [118]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [119]:
x[3]

3

In [120]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [122]:
x[3:9:2]

array([3, 5, 7])

In [ ]:
[x[3], x[5], x[8]]

In [124]:
ind = [3, 5, 8]

In [125]:
x[ind]

array([3, 5, 8])

In [126]:
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [127]:
x =x.reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
x[row, col]

array([ 1,  6, 11])

In [129]:
x[0, col]

array([1, 2, 3])

In [130]:
x[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [131]:
col = [True, False, True, True]
x[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array的比较

In [135]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [136]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [137]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [138]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [139]:
X

array([[4, 0, 9, 5],
       [3, 0, 9, 5],
       [6, 6, 7, 5],
       [9, 8, 5, 8]])

In [140]:
X < 6

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

In [141]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [142]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [143]:
np.sum(x <= 3)

4

In [144]:
np.count_nonzero(x <= 3)

4

In [145]:
np.any(x == 0)

True

In [146]:
np.any(x < 0)

False

In [148]:
np.all(x >= 0)

True

In [149]:
np.sum(X % 2 == 0)

7

In [150]:
np.sum(X % 2 == 0, axis=1)

array([2, 1, 2, 2])

In [151]:
np.all(X > 0, axis=1)

array([False, False,  True,  True])

In [154]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [157]:
np.sum((x > 3) & (x < 10))  # & \

6

In [159]:
np.sum(~(x == 0))

15

In [160]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [161]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [163]:
X[X[:, 3] % 2 == 0, :]

array([[9, 8, 5, 8]])