# Numpy.array基础

In [71]:
import numpy

In [72]:
numpy.__version__

'1.16.2'

In [73]:
import numpy as np

In [74]:
np.__version__

'1.16.2'

## Python List的特点

In [75]:
L = [i for i in range(10)]

In [76]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [78]:
L[5] = "Machine Learning"

In [79]:
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [80]:
import array

In [81]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[5]

5

In [83]:
arr[5] = 100

In [84]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [85]:
arr[5] = 'Machine Learning'

TypeError: an integer is required (got type str)

## numpy.arrary

In [86]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
nparr[5]

5

In [88]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [89]:
nparr[5] = 'Machine Learning'

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [ ]:
nparr.dtype

In [ ]:
nparr[3] = 3.14
nparr

In [ ]:
nparr.dtype

In [ ]:
nparr2 = np.array([1, 2, 3.0])

In [ ]:
nparr2.dtype

## 其他创建numpy.arrary的方法

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10).dtype

In [ ]:
np.zeros(10, dtype=int32)

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.zeros((3, 5))

In [ ]:
np.zeros(shape=(3, 3, 3), dtype = int)

In [ ]:
np.ones((3, 5))

In [ ]:
np.full(shape=(3, 5), fill_value=666)

### arange

In [ ]:
[i for i in range(0, 20, 2)]

In [ ]:
np.arange(0, 20, 2)

In [90]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [91]:
np.arange(0, 20, 0.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8])

In [92]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [94]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [95]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [96]:
np.random.randint(0, 10)

7

In [97]:
np.random.randint(0, 10, 10)

array([6, 4, 3, 8, 5, 3, 3, 5, 9, 9])

In [98]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
np.random.randint(4, 8, size=10)

array([5, 4, 4, 4, 6, 5, 6, 5, 4, 4])

In [100]:
np.random.randint(4, 8, size=(3, 5))

array([[5, 7, 7, 6, 4],
       [4, 6, 5, 5, 7],
       [6, 6, 4, 6, 4]])

In [101]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [102]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [103]:
np.random.random()

0.2811684913927954

In [104]:
np.random.random((3, 5))

array([[0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625],
       [0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ],
       [0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ]])

In [105]:
np.random.normal()

-0.21326813235544162

In [106]:
np.random.normal(10, 100)

54.07669166918434

In [107]:
np.random.normal(0, 1, (3, 5))

array([[ 0.69339587,  0.03820097, -0.18592982, -0.35371521, -1.95332994],
       [-0.34376486, -1.47693162, -0.70022971,  0.77605168,  1.18063598],
       [ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ]])

In [108]:
np.random.normal?

In [109]:
np.random?

In [110]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

## Numpy.array的基本操作

In [111]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [113]:
x.ndim

2

In [114]:
x.shape

(3, 5)

In [115]:
x.size

15

### numpy.array的数据访问

In [116]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [117]:
x[0][0]

0

In [118]:
x[(0, 0)]

0

In [119]:
x[0, 2]

2

In [123]:
x[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
x[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [125]:
x[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [126]:
x[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [127]:
x[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [129]:
x[0].ndim

1

In [130]:
subx = x[:2, :3]
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [131]:
subx[0, 0] = 100

In [133]:
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [134]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [135]:
x[0, 0] = 0
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [136]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [137]:
subx = x[:2, :3].copy()
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [138]:
subx[0, 0] = 100
subx

array([[100,   1,   2],
       [  5,   6,   7]])

In [139]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [140]:
x.shape

(3, 5)

In [141]:
x.ndim

2

In [145]:
x.reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [146]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [147]:
x.reshape(5, - 1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 合并操作

In [148]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [149]:
x

array([1, 2, 3])

In [150]:
y

array([3, 2, 1])

In [151]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [153]:
z = np.array([666, 666, 666])

In [154]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [155]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [156]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [159]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions

In [158]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [160]:
A2 = np.concatenate([A, z.reshape(1, -1)])

In [161]:
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [162]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [163]:
B = np.full((2, 2), 100)

In [165]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [166]:
np.hstack([A,z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [167]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
x1, x2, x3 = np.split(x, [3, 7])

In [169]:
x1

array([0, 1, 2])

In [170]:
x2

array([3, 4, 5, 6])

In [171]:
x3

array([7, 8, 9])

In [172]:
x1, x2 = np.split(x, [5])

In [173]:
x1

array([0, 1, 2, 3, 4])

In [174]:
x2

array([5, 6, 7, 8, 9])

In [175]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [176]:
A1, A2 = np.split(A, [2])

In [177]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [178]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [179]:
A1, A2 = np.split(A, [2] ,axis=1)

In [180]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [181]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [182]:
upper, lower = np.vsplit(A, [2])

In [183]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [184]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [185]:
left, right = np.hsplit(A, [2])

In [186]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [187]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [188]:
data = np.arange(16).reshape((4, 4))

In [189]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [194]:
X, y = np.hsplit(data, [-1])

In [195]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [196]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [197]:
y[:, 0]

array([ 3,  7, 11, 15])