# 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [5]:
X = iris.data
y = iris.target

In [6]:
X.shape

(150, 4)

In [7]:
y.shape

(150,)

### train_test_split

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
shuffle_indexes = np.random.permutation(len(X))

In [11]:
shuffle_indexes

array([ 97, 133,  13,  60,  95, 105,  22,   2,  74,  49,  90, 127,   8,
        55, 131,  37, 106,   9, 146, 137,  51, 109,  42,  98,  79, 130,
        73,  87, 141, 107,  70,  19,  18,  83,   6,  15,  52,  76, 122,
        67, 115,  17, 135, 134,  48,  25, 147,  50,  12, 129,  69,  35,
        53, 100,   4,  11, 117,   5,   1, 110,  65, 132,  46,  43,  81,
        91,  16,  39, 124, 140,  54,  27,  88, 149,  47,  59, 114, 112,
        31,  44, 116,  20, 143, 139,  80,  58,  33,  34,  93, 108,  72,
        71,  40,  99, 138,  63, 128,  56,  10,  14, 121, 123,  38, 101,
       111, 126,  82, 113,  57,  75,   7,  29, 136,  94,  84,  61,  24,
       142,  36, 104,  85,  86,  92,  77,  28, 103, 148,  78,  89, 102,
       125,  30,  21,  66, 118, 145,  62, 120,   0,  41,  32, 119,   3,
        68,  64, 144,  23,  96,  45,  26])

In [13]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [14]:
test_size

30

In [15]:
test_indexes = shuffle_indexes[: test_size]
train_indexes = shuffle_indexes[test_size: ]

In [16]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [17]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [18]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用算法

In [19]:
from playML.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [21]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [23]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [24]:
from playML.kNN import KNNClassifier

In [25]:
my_knn_clf = KNNClassifier(k=3)

In [26]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [27]:
y_predict = my_knn_clf.predict(X_test)

In [28]:
y_predict

array([1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2,
       0, 1, 1, 0, 2, 1, 2, 2])

In [29]:
y_test

array([1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2,
       0, 1, 1, 0, 1, 1, 2, 2])

In [30]:
sum(y_predict == y_test)

29

In [31]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [34]:
print(X_train.shape)
print(y_train.shape)

(112, 4)
(112,)


In [35]:
print(X_test.shape)
print(y_test.shape)

(38, 4)
(38,)
