# 精准率和召回率的平衡

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()
y[digits.target == 9] = 1
y[digits.target != 9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [4]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
log_reg.score(X_test, y_test)

D:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.9755555555555555

In [5]:
y_predict = log_reg.predict(X_test)

In [6]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [7]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [9]:
precision_score(y_test, y_predict)

0.9473684210526315

In [11]:
recall_score(y_test, y_predict)

0.8

In [12]:
log_reg.decision_function(X_test)

array([-22.05705181, -33.02949573, -16.21340238, -80.37917009,
       -48.25125209, -24.54010044, -44.39166152, -25.04298784,
        -0.97831701, -19.71745321, -66.2513864 , -51.09609927,
       -31.49354859, -46.05334586, -38.6788697 , -29.80474166,
       -37.5885736 , -82.57576637, -37.81902892, -11.01172596,
        -9.17441466, -85.1300934 , -16.71622699, -46.2373814 ,
        -5.33001429, -47.9176172 , -11.66732594, -39.19614376,
       -25.25298529, -14.36652407, -16.99787221, -28.91910077,
       -34.33945987, -29.47614656,  -7.85819265,  -3.82095014,
       -24.08174422, -22.16364571, -33.61231771, -23.14031933,
       -26.91810677, -62.38943784, -38.85701958, -66.77268117,
       -20.14492423, -17.47892943, -18.06805716, -22.22229886,
       -29.62307347, -19.73172345,   1.49545888,   8.32075374,
       -36.29320492, -42.50740983, -25.90461737, -34.98965016,
        -8.42018324, -50.04725465, -51.48215611,  19.88957373,
        -8.91894758, -31.99350749, -11.66107835,  -0.47

In [13]:
log_reg.decision_function(X_test)[: 10]

array([-22.05705181, -33.02949573, -16.21340238, -80.37917009,
       -48.25125209, -24.54010044, -44.39166152, -25.04298784,
        -0.97831701, -19.71745321])

In [14]:
log_reg.predict(X_test)[: 10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
decision_scores = log_reg.decision_function(X_test)

In [19]:
np.min(decision_scores)

-85.68617092628044

In [20]:
np.max(decision_scores)

19.889573725637934

In [21]:
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [22]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [23]:
precision_score(y_test, y_predict_2)

0.96

In [24]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [25]:
y_predict_3 = np.array(decision_scores >= -5, dtype='int')
confusion_matrix(y_test, y_predict_3)

array([[390,  15],
       [  5,  40]], dtype=int64)

In [26]:
precision_score(y_test, y_predict_3)

0.7272727272727273

In [27]:
recall_score(y_test, y_predict_3)

0.8888888888888888